
// Code
// Testcase
// Testcase
// Test Result
// 389. Find the Difference
// Easy
// Topics
// premium lock icon
// Companies
// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"
 

// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.

class Solution {
    public char findTheDifference(String s, String t) {
        int[] freqs = new int[26];
        int[] freqt = new int[26];

        for (char c: s.toCharArray())
            freqs[c-'a']++;

        for(char c : t.toCharArray())
            freqt[c-'a']++;

        for(int i=0;i<26;i++){
            if(freqs[i]<freqt[i])
                return (char)(i+'a');
        }
        return 'a';
    }

    public static void main(String[] args) {
        detectcyleinlinkedlist sol = new detectcyleinlinkedlist();

        // String s = "abcd", t = "abcde";
        // String s = "bhf", t = "bhuf";
        // String s = "gvhh", t = "ahgvh";
        String s = "z", t = "zz";


        System.out.println(sol.findTheDifference(s, t));
    }
}